feat(install-profile): check if profile exists
  ## what
  - Check if dotbot profile file exists before continuing

  ## how
  - loop through command line arguments
    - if profile doesn't exist
      - print warning
      - flag to exit
  - check if exit flag is set
    - exit in non zero code
  - clear variables used

  ## why
  - Better to check beforehand if a profile file exists.

  ## where
  - ./install-profile

  ## usage
  ./install-profile < profile >
  Ex: ./install-profile profile1

diff --git a/install-profile b/install-profile
--- a/install-profile
+++ b/install-profile
@@ -18,6 +18,35 @@ BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 cd "${BASE_DIR}"
 git submodule update --init --recursive
 
+# ------------------------------------------------------------------------------------------------ #
+# Verify dotbot profile exists
+# Checks if the file exists in meta/profiles/ folder
+
+exitIfProfileNotFound=false    # used as a flag to exit IF a profile is NOT found
+for profile in ${@}; do
+  # check if the profile filepath doesn't exist
+  #   print message
+  #   flag variable to exit
+
+  profileFilepath="${BASE_DIR}/${META_DIR}/${PROFILES_DIR}/${profile}"
+
+  if [[ ! -e $profileFilepath ]]; then
+    echo -e "Dotbot profile \\033[1;31m$profileFilepath \\033[0mNOT found"
+
+    exitIfProfileNotFound=true
+  fi
+done
+
+# exit if a profile filepath is NOT found
+if [[ $exitIfProfileNotFound == true ]]; then
+  echo -e "\nexiting"
+  exit 1
+fi
+
+# cleanup variables
+unset exitIfProfileNotFound
+
+# ------------------------------------------------------------------------------------------------ #
 
 while IFS= read -r config; do
     CONFIGS+=" ${config}"
